DATABASE_URL_PREVISAO = "postgresql://postgres:%24Rayan77%24Crvg@db.txuylmwpzzfyiaughzin.supabase.co:5432/postgres"
DATABASE_URL_PALPITES = "postgresql://postgres:%24Rayan77%24Crvg@db.umpwzetgfgjtiihewbyr.supabase.co:5432/postgres"
API_FOOTBALL_KEY = "78df7820bf2ee8de28eff961fb317285"